version: "3"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/alerha/db:/data/db
  api:
    build: ./alerha-api
    restart: always
    depends_on:
      - mongo
  nginx:
    build: ./alerha-nginx
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/letsencrypt
      - ./webroot:/var/www/html
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot-etc:/etc/letsencrypt
  #     - ./certbot-var:/var/lib/letsencrypt
  #     - ./webroot:/var/www/html
  #   depends_on:
  #     - nginx
  #   command: certonly --webroot -w /var/www/html --email test@alerha.com --agree-tos --no-eff-email --force-renewal -d alerha.com -d www.alerha.com -d api.alerha.com
