version: "3"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/alerha/db:/data/db
  api:
    build: ./alerha-api
    restart: always
    depends_on:
      - mongo
  nginx:
    build: ./alerha-nginx
    depends_on:
      - api
    ports:
      - "8080:80"
