version: "3"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/alerha/db:/data/db
  api:
    build: ./alerha-api
    restart: always
    depends_on:
      - mongo
  nginx:
    build: ./alerha-nginx
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/letsencrypt
      - ./webroot:/var/www/html