version: "3"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/alerha/db:/data/db
      - /data/alerha/configdb:/data/configdb
  api:
    build: ./alerha-api
    restart: always
    depends_on:
      - mongo
  nginx:
    build: ./alerha-nginx
    restart: always
    depends_on:
      - api
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/letsencrypt
      - ./webroot:/var/www/html