version: "3"
services:
  mongo:
    image: mongo
    restart: always
    external_links:
      - "mongo"
    volumes:
      - /data/alerha/db:/data/db
  app:
    build: ./alerha-app
    external_links:
      - "app"
    depends_on:
      - mongo
  nginx:
    build: ./alerha-nginx
    depends_on:
      - app
    ports:
      - "8080:80"
